thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
34019348,34019348,null,1,2,Tue Dec 01 11:30:00 EST 2015,3500858,"<p>I am experimenting with fiware and I would like to setup a VM with those 2 compoments in order to have an environment to be used with IoT devices.<br>	I have been able (let me say with a great effort) to create a VM with the two components installed, by using the base contextBroker instance and building IoTAgent from source and then installing the generated RPMs. ContextBroker seems to work fine, because I can query for entities and I get 200 status as response, but if I try to create a service in IoTA I get no response, so I guess there is something wrong with the configuration.<br>	I'll list all the steps I have performed so troubleshooting can be easier:  </p>		<ul>	<li>Deployed the VM in fiware Lab Cloud (orion-psb-image-R4.4)</li>	<li>Opened ports in the security group </li>	<li>Associated a floating IP to the VM</li>	<li>Built IoTAgent</li>	<li>Generated and installed RPMs packages</li>	<li>Set PATH and LD_LIBRARY_PATH in .bashrc to start iotagent properly</li>	<li>Created the configuration file <em>"config.json"</em> in <em>/etc/iot</em> as described on <a href="https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus/blob/develop/doc/deploy.md#3-iotagent-configuration" rel="nofollow">GitHub</a> (I used the example one)</li>	<li>Started iotagent as a service with the command <code>sudo service iotagent start protocol</code></li>	<li>Used the figway scripts to create a service, but the script hangs</li>	</ul>		<p>Does <em>iotagent_protocol.conf</em> file in <em>/usr/local/iot/config</em> need any particular configuration as well or is there in general something I am missing or that I could check? Also, if I check the log in <em>/tmp</em> I can see this message: <code>OAuth for northbound is not configured</code>. Is authentication needed? In GitHub README the example configuration file has no authentication.</p>	"
34019348,55798425,34019348,3,0,Tue Dec 01 13:38:00 EST 2015,4340880,"We would need more information to diagnose your problem properly. Authentication is not needed in order to use the IoT Agent; if no authentication information is configured, the IOTA doesn't try to get the token and authenticate requests. If the log is showing that line and you haven't configured anything, it may be just a warning (some bugs have been reported of error lines shown as errors where they where only warnings). Are there any more errors in the log? Did you use netstat to check if the process is really listening in the appropriate port?"
34019348,55798751,34019348,3,0,Tue Dec 01 13:47:00 EST 2015,3500858,"At the end it was just a firewall problem, I flushed iptables leaving only the security group VM policies and now I am able to reach the endpoint."
34019348,34022078,34019348,2,2,Tue Dec 01 13:50:00 EST 2015,3500858,"<p>The problem was the firewall, so a simple<br>	<code>	sudo iptables -F	</code>  </p>		<p>solved the problem, leaving only the security policies specified in the VM security group from the fiware cloud.</p>	"
