thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
34354575,34354575,null,1,2,Fri Dec 18 11:25:00 EST 2015,4361588,"<p>I am trying to control an LED on my Raspberry Pi with the Pubnub platform.	I just started and I tried this tutorial:</p>		<p><a href="https://www.pubnub.com/blog/2015-05-27-internet-of-things-101-getting-started-w-raspberry-pi/" rel="nofollow">https://www.pubnub.com/blog/2015-05-27-internet-of-things-101-getting-started-w-raspberry-pi/</a></p>		<p>However, when I want to execute a Python file that imports the Pubnub library with the following line: </p>		<p><code>from pubnub import Pubnub</code></p>		<p>I get this error message: </p>		<p><code>ImportError: cannot import name Pubnub</code></p>		<p>I did everything exactly as told in the tutorial. I even copied the .py classes from their Github repository.</p>		<p>This is my class:</p>		<pre><code>import RPi.GPIO as GPIO	import time	import sys	from pubnub import Pubnub		GPIO.setmode (GPIO.BCM)		LED_PIN = 17		GPIO.setup(LED_PIN,GPIO.OUT)		pubnub = Pubnub(publish_key='xxxx', subscribe_key='xxxx')		channel = 'disco'		def _callback(m, channel):	        print(m)	        if m['led'] == 1:	                for i in range(6):	                    GPIO.output(LED_PIN,True)	                    time.sleep(0.5)	                    GPIO.output(LED_PIN,False)	                    time.sleep(0.5)	                    print('blink')		def _error(m):	        print(m)		pubnub.subscribe(channels=channel, callback=_callback, error=_error)	</code></pre>	"
34354575,56450693,34354575,3,0,Fri Dec 18 11:28:00 EST 2015,4889267,"Is the pubnub.py file in the same directory as the file you are executing, or on the pythonpath?"
34354575,56450943,34354575,3,0,Fri Dec 18 11:35:00 EST 2015,4889267,"Try running: help('modules') and see which modules are listed. Look for your Pubnub"
34354575,56451005,34354575,3,0,Fri Dec 18 11:37:00 EST 2015,4361588,"I did this for setup python and pubnub:		Install Python:	pi@raspberrypi ~$ sudo apt-get install python-dev		Install pip:	pi@raspberrypi ~$ sudo apt-get install python-pip		install PubNub:	pi@raspberrypi ~$ sudo pip install pubnub"
34354575,56451081,34354575,3,0,Fri Dec 18 11:39:00 EST 2015,4361588,"The pubnub module is listed when I execute help('modules')."
34354575,56451117,34354575,3,0,Fri Dec 18 11:40:00 EST 2015,4361588,"@Alan: the pubnub.py file is located at: /usr/local/lib/python2.7/dist-packages/pubnub.py		My python class to control the led is in my home directory."
34354575,56451292,34354575,3,0,Fri Dec 18 11:45:00 EST 2015,4915222,"Do you start your script with python3 or python2? Both versions may be installed on your raspi. But pubnub is only installed for python2 (2.7) - I assume."
34354575,56451412,34354575,3,0,Fri Dec 18 11:48:00 EST 2015,4361588,"I start my script using "python remote-led.py" in the command line. I assume if i type "python2.7 remote-led.py" it runs with 2.7 right? However, the output is the same error message."
34354575,34354881,34354575,2,2,Fri Dec 18 11:41:00 EST 2015,3782044,"<p>try:</p>		<pre><code>pip install pubnub	</code></pre>		<p>I did it and it works fine. No need to github anything.	pip is available for Linux and Windows.</p>	"
34354575,56453444,34354881,3,0,Fri Dec 18 12:48:00 EST 2015,4361588,"Ok it was not corrupt. I installed it without cache and still get this error when executing "import pubnub" from python:		Traceback (most recent call last):	  File "<stdin>", line 1, in <module>	  File "pubnub.py", line 2531, in <module>	    class PubnubHTTPAdapter(HTTPAdapter):	NameError: name 'HTTPAdapter' is not defined"
34354575,56453535,34354881,3,0,Fri Dec 18 12:51:00 EST 2015,4361588,"@PeterPaulKiefer the error message changed from "cannot import name pubnub" to "NameError: name 'HTTPAdapter' is not defined". Which is caused by the same line of code. I rename the variable name though."
34354575,56453690,34354881,3,0,Fri Dec 18 12:54:00 EST 2015,4915222,"@Jenkins I looked into the pubnub code and saw that they import the HTTPAdapter in a try catch block. If it fails they simply pass. That means you will not be notified if the adapter can not be loaded i.e. is not installed. Have you tried to reinstall the requests package as kotletSchabowy recommended above?"
34354575,56454027,34354881,3,0,Fri Dec 18 13:04:00 EST 2015,4361588,"@PeterPaulKiefer I've overseen the reinstall requests. I did it and the HTTP Adapter error is now fixed! Also the initial ImportError is gone. I am now able to control my LED over the internet. Thank you guys so much."
34354575,56454308,34354881,3,0,Fri Dec 18 13:11:00 EST 2015,4915222,"@Jenkins The helping tips came from Kotlet within two comments. I upvoted theese comments to mark their importence for this conversation."
34354575,56451219,34354881,3,0,Fri Dec 18 11:43:00 EST 2015,4361588,"I already did this when I setup the project. See the comment above. Do I need to execute it again?"
34354575,56451240,34354881,3,0,Fri Dec 18 11:44:00 EST 2015,4361588,"When I execute the command again, it says that the requirement is already satisfied."
34354575,56451367,34354881,3,0,Fri Dec 18 11:47:00 EST 2015,3782044,"can you do "import pubnub"? Please post  dir(pubnub)."
34354575,56451503,34354881,3,0,Fri Dec 18 11:50:00 EST 2015,4361588,"You mean just write "import pubnub" in a .py? I did it and got no error, when executing. When I change my remote-led.py class from "from pubnub import Pubnub" to "import pubnub" I get the error: "ImportError: No module named pubnub". My pubnub.py is in the directory: /usr/local/lib/python2.7/dist-packages/pubnub.py."
34354575,56451664,34354881,3,0,Fri Dec 18 11:55:00 EST 2015,3782044,"just fire up python on the console and enter "import pubnub". If this gives no error, enter dir(pubnub) and post the result. This is my result (some deleted): >>> dir(pubnub)	['AES', 'EmptyLock', 'HTTPAdapter', 'HTTPClient', 'Pubnub', ...] You should find the 'Pubnub' list element. Then enter 'from pubnub import Pubnub'. If this gives no error in the console we can investigate further."
34354575,56451721,34354881,3,0,Fri Dec 18 11:56:00 EST 2015,4361588,">>> dir(pubnub)	['__builtins__', '__doc__', '__file__', '__name__', '__package__']. Looks different then yours."
34354575,56451867,34354881,3,2,Fri Dec 18 12:01:00 EST 2015,3782044,"I recommend to remove all pubnub data and do a "pip install pubnub" again"
34354575,56452010,34354881,3,0,Fri Dec 18 12:06:00 EST 2015,4361588,"I did "pip uninstall pubnub" and then "pip install pubnub". Now I get "NameError: name 'HTTPAdapter' is not defined" when I type "import pubnub" in the python console."
34354575,56452351,34354881,3,2,Fri Dec 18 12:17:00 EST 2015,3782044,"pubnub does: "import requests	    from requests.adapters import HTTPAdapter" Maybe it is removed. Do a "pip install requests""
34354575,56452408,34354881,3,0,Fri Dec 18 12:18:00 EST 2015,4361588,"What does that even mean? I tried to uninstall everything and reinstall it. But without my limited knowledge it seems I'm making things worse."
34354575,56452527,34354881,3,0,Fri Dec 18 12:21:00 EST 2015,4361588,"When I do "pip uninstall pubnub" and "pip install pubnub" I found out, that pip uses a cached version of the pubnub.tar.gz. How can I remove this cached version? Maybe it is corrupt."
34354575,56452952,34354881,3,0,Fri Dec 18 12:33:00 EST 2015,3782044,"If using pip 6.0 or newer, try using the --no-cache-dir option found it here: https://stackoverflow.com/questions/9510474/removing-pips-cache"
34354575,56453228,34354881,3,0,Fri Dec 18 12:41:00 EST 2015,4915222,"@Jenkins You used pubnub as the variable name of your instance object. Perhaps your package variable, which is called pubnub too, would be superseded by the local variable. ?? I do not think that the cached installation package is corrupt. In that case pip would show an error message. (Is there one in `$HOME/.pip/pip.log` ?)"
34354575,40510582,34354575,2,8,Wed Nov 09 15:31:00 EST 2016,7137126,"<p>If you're running into this since early November 2016; the pubnub API has changed in version 4.0.</p>		<pre><code>from pubnub import Pubnub	</code></pre>		<p>does not work. It's now (to my best knowledge):</p>		<pre><code>from pubnub.pubnub import PubNub	</code></pre>	"
34354575,69664955,40510582,3,0,Mon Dec 19 23:30:00 EST 2016,5045925,"This solved my problem! Thank you!"
34354575,75747561,40510582,3,0,Mon Jun 05 16:20:00 EDT 2017,5167801,"Thanks that did the trick. However, the API is changed so much that the old Raspberry Pi tutorials are completely not working. Does any one has a working example of PubNub python new API ?"
34354575,42034584,34354575,2,0,Fri Feb 03 23:22:00 EST 2017,3726682,"<p>I experienced the same problem on my Raspberry Pi 3. It ended up being a very silly issue! I had a file called pubnub.py which is why when I ran my script when it was located in the folder "Desktop" it didn't work. However, after I brought it up to its parent directory "pi" it imported pubnub without an issue!</p>	"
