thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
48472482,48472482,null,1,0,Sat Jan 27 04:04:00 EST 2018,8794475,"<p>I am creating IoT Edge using the blog <a href="https://docs.microsoft.com/en-us/azure/iot-edge/quickstart" rel="nofollow noreferrer">https://docs.microsoft.com/en-us/azure/iot-edge/quickstart</a>.</p>		<p>I have installed Python 2.7, azure-iot-edge-runtime-ctl on a Windows 1709 Virtual machine.	I am running Docker version 17.09 CE and Windows Containers. When I am trying to setup IoT-edge runtime module in Windows 10 VM. </p>		<pre><code>iotedgectl setup --connection-string "{device connection string}" --auto-cert-gen-force-no-passwords	</code></pre>		<p>when I am running above command facing the issue, Any suggestions appreciated. </p>		<p>Traceback (most recent call last):</p>		<pre><code>File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main	  "__main__", fname, loader, pkg_name)	  File "c:\python27\lib\runpy.py", line 72, in _run_code	    exec code in run_globals	  File "C:\Python27\Scripts\iotedgectl.exe\__main__.py", line 9, in &lt;module&gt;	  File "c:\python27\lib\site-packages\edgectl\__init__.py", line 25, in coremain	    return cli.execute_user_command()	  File "c:\python27\lib\site-packages\edgectl\edgecli.py", line 54, in execute_user_command	    (is_valid, execute_deployment_cmd) = self._process_cli_args()	  File "c:\python27\lib\site-packages\edgectl\edgecli.py", line 358, in _process_cli_args	    return args.func(args)	  File "c:\python27\lib\site-packages\edgectl\edgecli.py", line 379, in _parse_edge_command	    if EdgeDefault.is_deployment_supported(self._deployment):	  File "c:\python27\lib\site-packages\edgectl\default.py", line 99, in is_deployment_supported	    client = EdgeDockerClient()	  File "c:\python27\lib\site-packages\edgectl\dockerclient.py", line 13, in __init__	    self._client = docker.DockerClient.from_env()	  File "c:\python27\lib\site-packages\docker\client.py", line 81, in from_env	    **kwargs_from_env(**kwargs))	  File "c:\python27\lib\site-packages\docker\client.py", line 38, in __init__	    self.api = APIClient(*args, **kwargs)	  File "c:\python27\lib\site-packages\docker\api\client.py", line 131, in __init__	    'Install pypiwin32 package to enable npipe:// support'	docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support	</code></pre>		<p>Any suggestions, please.</p>	"
48472482,48495913,48472482,2,0,Mon Jan 29 06:56:00 EST 2018,8546089,"<p>Is the version of Python you have installed 2.7.14?It seems that pypiwin32 package has not been installed in your PC.Please use <code>pip</code> to install this package like executing the following command in your computer:</p>		<pre><code>pip install pypiwin32	</code></pre>	"
48472482,48496810,48472482,2,4,Mon Jan 29 08:02:00 EST 2018,3321441,"<p><strong>Problem Solution:</strong></p>		<ul>	<li>The â€œnpipe:// brokenâ€? problem reported here applicable to Windows machines and is a problem whether Linux or Windows containers are used in Docker.</li>	<li><a href="https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl" rel="nofollow noreferrer">azure-iot-edge-runtime-ctl 1.0.0rc19</a> was released recently which addresses this issue by ensuring the correct pypiwin32 package is installed.</li>	<li><p>To get the latest bits execute:</p>		<pre><code>$&gt; pip install -U azure-iot-edge-runtime-ctl	</code></pre></li>	<li><p>Check installed version:</p>		<pre><code>$&gt; iotedgectl --version	iotedgectl 1.0.0rc19	</code></pre></li>	</ul>		<p><strong>Summary of issue:</strong></p>		<ul>	<li>iotedgectl uses library docker-py to communicate with Docker for kick starting and controlling the Edge runtime.</li>	<li>docker-py uses pypiwin32 for communicating with docker over named pipes (npipe). With the release of v222 of pypiwin32 docker-py is broken on Windows hosts.</li>	<li>As a quick workaround until the official fixes can be incorporated, iotedgectl was released which ensures that correctly working dependencies get pulled in.</li>	</ul>	"
