thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
53759340,53759340,null,1,1,Thu Dec 13 10:05:00 EST 2018,10785302,"<p>I am new to the python coding and is still learning, so most probably this will be a stupid question for many. But what I am looking for is logic, not code.</p>		<p>My Scenario:	I have an IoT sensor, that will send me data over serial as JSON files on regular intervals. The file will always be the same name. Now I am writing a python script to read this JSON file in an infinite loop. 	The idea is that if there is no data in the JSON, then the loop should just break and send me a message. Otherwise, just parse the dictionary.</p>		<p>I have written it like this with a try and except.</p>		<pre><code>def readDataInLoop(self, ):	    while True:            		        try:	            # Reading json	            with open('dummyzigbee.json') as f:	                data = json.load(f)		                # Check Data: If Data is empty, exit loop with error message	                if not data:	                    print("Error!! No data recieved ...")	                    print("Conenction lost at {} ".format(time.asctime(time.localtime(time.time()))))                    	                    break                    		                else:	                    # If data is recieved then parse the data	                    self.parseData(data)	        except:	            pass		        # Give some rest to processor	        time.sleep(1)	</code></pre>		<p>This seems to work but I am looking for an efficient manner. I am not sure if this is a good approach or a bad approach.</p>	"
53759340,94370730,53759340,3,2,Thu Dec 13 10:08:00 EST 2018,6260170,"this looks ok mostly but i would remove the `try-except: pass`, this will mask any errors that occur, if you need to catch a specific exception then do so and log it appropriately"
53759340,94370775,53759340,3,2,Thu Dec 13 10:09:00 EST 2018,1084416,"I wonder whether this would be better suited on [codereview.se]. However, you need to make sure your code really works."
53759340,94370873,53759340,3,0,Thu Dec 13 10:12:00 EST 2018,5267751,"If the code works correctly it would also be on topic for code review. Although the first line is syntactically incorrect."
53759340,94370964,53759340,3,1,Thu Dec 13 10:14:00 EST 2018,4046632,"couple of questions - at the very begining (before receiving any data) I assume json will not exists. Your try/except block should capture that particular error (FiileNotFound), not like now - catch all exceptions. What will happen if no new data - do you get empty json (i.e. the existing one is overwritten)  or you will have the previous one (in which case it will not be empty and your if condition will be evaluated False). Finally - if you get empty json from the sensor that does not mean connection is lost."
53759340,94372795,53759340,3,0,Thu Dec 13 11:08:00 EST 2018,10785302,"@buran Very nice ideas. I will implement those in my code. Thanks for that"
53759340,94370980,53759340,3,0,Thu Dec 13 10:15:00 EST 2018,3728958,"The code itself looks pretty fine to me. It's pythonic and robust. Only I would suggest to use `except IOError:`, because that will allow other errors to be shown. I wonder, however, what's the purpose of breaking the loop. If there is no data, your script will stop - is that what you plan or would you not rather wait another second and try again?"
53759340,94371212,53759340,3,0,Thu Dec 13 10:21:00 EST 2018,8334261,"Is it relevant that you read the file in equidistant time invervals? This is not the case the way you have written your code. Here it is `time to execute try-except + 1sec`."
53759340,94371835,53759340,3,0,Thu Dec 13 10:40:00 EST 2018,388787,"You should use change notification on the file and only reread the file when it changes. Under linux this can be done with inotifiy. Don't forget to properly replace the file so that it isn't read when partially written with mkstemp and rename."
53759340,94372258,53759340,3,0,Thu Dec 13 10:52:00 EST 2018,10785302,"Thanks you all for your comments. @Chris_Rands yes, you are right! When I ran the code and had some eror and simply exited. So, yes this try except does not seems to work. I think it only works if I already know what error I will get and can handle them nicely."
