thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
56555909,56555909,null,1,0,Wed Jun 12 06:31:00 EDT 2019,3715264,"<p>I get an error when I am trying to push locally to a device. Although, I am able to ping it. </p>		<p>I am working on windows10 and running the cmd as an admin.</p>		<p>The below code has all the three commands I have used.	1.) â€œbalena scanâ€? discovers the available local device.	2.) â€œbalena pushâ€? does not work.	3.) but ping works successfully.</p>		<pre><code>D:\repository\FastBin\fast-bin-controller-dev&gt;balena scan	Reporting scan results	-	  host:          56b2f81.local	  address:       172.30.112.88	  dockerInfo:	    Containers:        1	    ContainersRunning: 1	    ContainersPaused:  0	    ContainersStopped: 0	    Images:            2	    Driver:            aufs	    SystemTime:        2019-06-12T06:28:30.26445254Z	    KernelVersion:     4.9.34+	    OperatingSystem:   Resin OS 2.12.7+rev2	    Architecture:      armv7l	  dockerVersion:	    Version:    17.06.0-dev	    ApiVersion: 1.31		D:\repository\FastBin\fast-bin-controller-dev&gt;ping 172.30.112.88		Pinging 172.30.112.88 with 32 bytes of data:	Reply from 172.30.112.88: bytes=32 time=1ms TTL=64	Reply from 172.30.112.88: bytes=32 time=1ms TTL=64	Reply from 172.30.112.88: bytes=32 time=1ms TTL=64	Reply from 172.30.112.88: bytes=32 time=1ms TTL=64		Ping statistics for 172.30.112.88:	    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),	Approximate round trip times in milli-seconds:	    Minimum = 1ms, Maximum = 1ms, Average = 1ms		D:\repository\FastBin\fast-bin-controller-dev&gt;balena push 172.30.112.88	Could not communicate with local mode device at address 172.30.112.88		Additional information may be available by setting a DEBUG=1 environment	variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"	on Linux or macOS.		If you need help, don't hesitate in contacting our support forums at	https://forums.balena.io		For bug reports or feature requests, have a look at the GitHub issues or	create a new one at: https://github.com/balena-io/balena-cli/issues/		</code></pre>		<p>What am I missing?</p>	"
56555909,56594807,56555909,2,0,Fri Jun 14 09:01:00 EDT 2019,3715264,"<p>The problem was that the version of the OS should be greater than or equal to 2.29 and mine was 2.12. After the upgrade, I was able to connect locally.</p>		<p>Thanks</p>	"
